"""empty message

Revision ID: 89ded566b928
Revises: f9a075ca46e9
Create Date: 2024-07-13 22:52:09.335210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ded566b928'
down_revision = 'f9a075ca46e9'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True), 
    sa.Column('resident', sa.String(length=255), nullable=True), 
    sa.Column('home_town', sa.String(length=255), nullable=True), 
    sa.Column('medical_history', sa.Text, nullable=True), 
    sa.Column('sex', sa.Boolean(), nullable=True), 
    sa.Column('identification', sa.String(length=12), nullable=True), 
    sa.Column('blood_group', sa.String(length=3), nullable=True), 
    sa.Column('height', sa.Integer(), nullable=True), 
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True), 
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_birth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
