"""empty message

Revision ID: e75c154255ca
Revises: 89ded566b928
Create Date: 2024-07-14 20:38:45.282292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e75c154255ca'
down_revision = '89ded566b928'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('relative',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True), 
    sa.Column('full_name', sa.String(length=255), nullable=True),  # Specify length for VARCHAR columns
    sa.Column('email', sa.String(length=255), nullable=True),  # Specify length for VARCHAR columns
    sa.Column('patient_id', sa.Integer(), nullable=False),  # Specify length for VARCHAR columns
    sa.Column('Relationship', sa.String(length=255), nullable=True),  # Specify length for VARCHAR columns
    sa.Column('date_birth', sa.Date(), nullable=True),
    sa.Column('resident', sa.String(length=255), nullable=True), 
    sa.Column('note', sa.Text, nullable=True), 
    sa.PrimaryKeyConstraint('id')
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relative')
    # ### end Alembic commands ###
